# 服务配置
server:
  port: 8090

# 启用Swagger文档
swagger.enable: true
# 启用全局方法日志
appMethodLogger.enable: true

# Https配置
sslserver:
  port: 443
  keyStore: .keystore
  keyStorePassword: changeit
  keyStoreType: JKS

# Spring配置
spring:
  http:
    multipart: #文件上传大小限制
      maxFileSize: 1024MB
      maxRequestSize: 10240MB
  jackson: # Jackson配置
    timeZone: GMT+8
    dateFormat: yyyy-MM-dd HH:mm:ss
  datasource: # 数据库配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot_demo?useUnicode=true
    username: root
    password: rootpwd

# MyBatis 配置
mybatis:
  mapper-locations: classpath:query/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Security配置
security:
  ignored:
    - assets/**
    - vendor/**
    - favicon.ico
    - login.html
